ASMA/tradingplatform/marketview/urls.py
from django.urls import path,re_path
from marketview import views

app_name = 'marketview'

urlpatterns = [
    re_path(r'^register/$',views.register,name='register'),
    re_path(r'^user_login/$',views.user_login,name='user_login'),
    # path('newstopic/',views.news_topic,name='news_topic'),
    path('news/',views.news,name='news'),
    path('foreign_market/',views.foreign_market,name='foreign'),
    path('search/',views.search,name='search')
]

ASMA/tradingplatform/tradingplatform/urls.py
from django.contrib import admin
from django.urls import re_path,path,include
from marketview import views

urlpatterns = [
    path("",views.index,name='index'),
    path("marketview/",include("marketview.urls", namespace='marketview')),
    re_path(r'^logout/$',views.user_logout,name='logout'),
    path("admin/", admin.site.urls),
]

ASMA/tradingplatform/marketview/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)


    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username
    
# class NewsTopic(models.Model):

#     news_topics = {
#         "blockchain":"Blockchain",
#         "earnings":"Earnings",
#         "ipo":"IPO",
#         "mergers_and_acquisitions":"Mergers & Acquisitions",
#         "financial_markets":"Financial Markets",
#         "economy_macro":"Economy",
#         "energy_transportation":"Energy & Transportation",
#         "finance":"Finance",
#         "life_sciences":"Life Sciences",
#         "manufacturing":"Manufacturing",
#         "real_estate":"Real Estate & Construction",
#         "retail_wholesale":"Retail & Wholesale",
#         "technology":"Technology"
#     }
#     topic = models.CharField(max_length=30,choices=news_topics)

#     def __str__(self):
#         return self.topic
    
class NewsList(models.Model):

    title = models.CharField(max_length=256)
    thumbnail = models.ImageField(blank=True)
    date = models.DateField(auto_now=True)
    time = models.TimeField(blank=True,auto_now=True)
    source = models.CharField(max_length=128)
    author = models.CharField(max_length=128)
    link = models.URLField(max_length=256,blank=True)
    summary = models.CharField(max_length=256,default='...')

    def __str__(self):
        return self.title
    

ASMA/tradingplatform/marketview/forms.py
from django import forms
from django.contrib.auth.models import User
from marketview.models import UserProfileInfo


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

# class NewsTopicForm(forms.ModelForm):
    

#     class Meta:
#         model = NewsTopic
#         fields = ('topic',)
#         widgets = {
#             'topic': forms.Select()
#         }

ASMA/tradingplatform/marketview/views.py
from django.shortcuts import render
from . import forms
from marketview.models import NewsList
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.contrib.auth import authenticate,login,logout
import pandas_datareader.av.time_series as ts
import pandas_datareader.nasdaq_trader as nt
import pandas as pd
import requests
import json
import plotly.graph_objects as go



@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':
        form = forms.UserForm(request.POST)
        profile_form = forms.UserProfileInfoForm(request.POST)

        if form.is_valid() and profile_form.is_valid():

            user = form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(form.errors,profile_form.errors)
    else:
        form = forms.UserForm()
        profile_form = forms.UserProfileInfoForm()

    user_dict = {'user_form':form,'profile_form':profile_form,'registered':registered}
    return render(request,'marketview/registration.html',context=user_dict)

def index(request):
    return render(request,'marketview/index.html')

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active")
            
        else:
            print("Someone tried to login and failed!")
            print(f"Username: {username} and password {password}")
            return HttpResponse("invalid login details supplied")
        
    else:
        return render(request,'marketview/login.html',{})
    
def news(request):

    temp = NewsList.objects.all()

    temp.delete()

    selected = False

    if request.method == 'POST':
        top = request.POST.get('topic')

        selected=True

        # top = NewsTopic.objects.get()
    
        news_dict = requests.get(f"https://www.alphavantage.co/query?function=NEWS_SENTIMENT&topics={top}&apikey=TRL8S38I56MBYQ4D").json()

        for feed in news_dict['feed']:

            tit = feed['title']
            thumb = feed['banner_image']
            d = feed['time_published'].split('T')[0]
            t = feed['time_published'].split('T')[1]
            src = feed['source']
            athr = ' '.join(feed['authors'])
            lnk = feed['url']
            smry = feed['summary']

            nslst = NewsList.objects.get_or_create(title=tit,thumbnail=thumb,date=d,time=t,source=src,author=athr,link=lnk,summary=smry)

        news_list = NewsList.objects.order_by('date')
        return render(request,'marketview/news.html',context={"news_list":news_list,"selected":selected})
    
    else:
        return render(request,'marketview/news.html',context={"selected":selected})
        
    
# def news_topic(request):


#     temp = NewsTopic.objects.all()
#     temp.delete()

#     if request.method == "POST":
#         form = forms.NewsTopicForm(request.POST)

#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('marketview:news'))
#         else:
#             print(form.errors)
#     else:
#         form = forms.NewsTopicForm()
        
#     return render(request,'marketview/newstopic.html',context={"select_topic":form})

def foreign_market(request):
    # ibm = dataread.Stocks.StockFrame() 
    # fig = go.Figure(data=[go.Candlestick(x=ibm.index,
    #                                      open=ibm['open'],high=ibm['high'],
    #                                      low=ibm['low'],close=ibm['close'])
    #                                      ]).to_html()
    # context = {'fig':fig}
    # df = ts.AVTimeSeriesReader(symbols='IBM',function='TIME_SERIES_INTRADAY',start='6/20/24',end='6/21/24',api_key="TRL8S38I56MBYQ4D").read()
    
    # time = df.index
    # open = df['open']
    # high = df['high']
    # low = df['low']
    # close = df['close']

    # url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol={sym}&interval=5minapikey=TRL8S38I56MBYQ4D'

    
    selected=True
    sym = request.GET.get('symbol')
    url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IBM&apikey=demo'
    r = requests.get(url)
    dat = r.json()
    times = [key for key in dat["Time Series (Daily)"].keys()]
    prices = [dat["Time Series (Daily)"][time] for time in times]
    opens = [inst['1. open'] for inst in prices]
    highs = [inst['2. high'] for inst in prices]
    lows = [inst['3. low'] for inst in prices]
    closes = [inst['4. close'] for inst in prices]
    
    return render(request,'marketview/foreign_markets.html',{"times":json.dumps(times),"opens":json.dumps(opens),"highs":json.dumps(highs),"lows":json.dumps(lows),"closes":json.dumps(closes),"selected":selected})

    
def search(request):
    
    if request.method == 'GET':
        key = request.GET.get('symbol')
        url = f'https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords={key}&apikey=TRL8S38I56MBYQ4D'
        data = requests.get(url).json()
        symbols = [item["1. symbol"] for item in data["bestMatches"]]
        return JsonResponse({ "data": symbols})
        

ASMA/tradingplatform/templates/marketview/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Archivo+Black&family=Bebas+Neue&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet">   
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/@trevoreyre/autocomplete-js/dist/style.css">
    <link rel="stylesheet" href="{% static "marketview/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "marketview/style.css" %}">
    <title>ASMA</title>
</head>
<body>

    

    <nav class="navbar navbar-expand-md shadow sticky-top">
        <div class="container-fluid">
          <a class="navbar-brand brand" href="{% url 'index' %}">
          <img src="{% static "marketview/logo-color-words.png" %}" height="50" alt="">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-set2" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Markets
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item text-set2" href="#">Indian</a></li>
                  <li><a class="dropdown-item text-set2" href="{% url 'marketview:foreign' %}">Foreign</a></li>
                  <li><a class="" href="#"></a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-set2" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Services
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item text-set2" href="#">Recommendations</a></li>
                  <li><a class="dropdown-item text-set2" href="#">Predictions</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item text-set2" href="#">Know how we do it</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link text-set2" href="{% url 'marketview:news' %}">News</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-set2" href="#">Pricing</a>
              </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                  <a href="{% url 'logout' %}" class="nav-link text-set2">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                  <a href="{% url 'marketview:user_login' %}" class="nav-link text-set2">Login</a>
              </li>
            {% endif %}
            </ul>
            <a href="{% url 'marketview:register' %}" class="d-flex nav-link">
              <button class="btn bg-set text-set bg-gradient" type="submit">Get Started</button>
            </a>
          </div>
        </div>
      </nav>

      {% block body-block %}
      {% endblock %}
      


      <script src="{% static "marketview/bootstrap.bundle.js" %}"></script>
      


</body>
</html>

ASMA/tradingplatform/templates/marketview/foreign_markets.html
{% extends "marketview/base.html" %}
<!DOCTYPE html>
{% block body-block %}


<script src="https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js"></script>

 


    <div id="can" class="jumbo container mt-5"></div>
        <script>
        

        var opens = "{{ opens }}"
        var highs = "{{ highs }}"
        var lows = "{{ lows }}"
        var closes = "{{ closes }}"
        var times = "{{ times }}"
        var times=JSON.parse(times.replace(/&quot;/g,'"'))
        var opens=JSON.parse(opens.replace(/&quot;/g,'"'))
        var highs=JSON.parse(highs.replace(/&quot;/g,'"'))
        var lows=JSON.parse(lows.replace(/&quot;/g,'"'))
        var closes=JSON.parse(closes.replace(/&quot;/g,'"'))
        const chartOptions = { layout: { textColor: 'black', background: { type: 'solid', color: 'white' } }, width: 800, height: 600 };
        const chart = LightweightCharts.createChart(document.getElementById('can'), chartOptions);
        const candlestickSeries = chart.addCandlestickSeries({
            upColor: '#26a69a', downColor: '#ef5350', borderVisible: false,
            wickUpColor: '#26a69a', wickDownColor: '#ef5350',
        });

        candlestickSeries.setData([
            {time: times[99], open: opens[99], high: highs[99], low: lows[99], close: closes[99]},
            {time: times[98], open: opens[98], high: highs[98], low: lows[98], close: closes[98]},
        ]);

        for (let i=opens.length-3;i>=0;i--){
            candlestickSeries.update({time: times[i], open: opens[i], high: highs[i], low: lows[i], close: closes[i]})
        }

        chart.timeScale().fitContent();
    </script>

    <!-- <div id="autocomplete" class="autocomplete container mt-3">
        <input class="autocomplete-input" placeholder="Search Symbols"/>
        <ul class="autocomplete-result-list"></ul>
    </div>

    <script>
        new Autocomplete('#autocomplete',{
            search: input =>{
                console.log(input)
                const url = 'search/?symbol=${input}'
                return new Promise(resolve =>{
                    fetch(url)
                    .then(response => response.json())
                    .then(data => {
                        resolve(data.data)
                    })
                })
            },
            onSubmit : result =>{
                window.open('/marketview/foreign_market/?symbol=${result}')
            }
        })
    </script> -->

    <!-- <form action="{% url 'marketview:foreign' %}" method="post">
        {% csrf_token %}
        <label for="symbol">Symbol:</label>
        <input list="symbols" name="symbol" id="symbol">
        <datalist id="symbols">
            <option value="IBM">IBM</option>
            <option value="AAPL">Apple</option>
            <option value="JSWSTEEL"></option>
            <option value="TATA">Tata</option>
            <option value="PATA"></option>
        </datalist>
        <input type="submit" value="GO">
    </form> -->


<!-- TradingView Widget BEGIN -->
<!-- <div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/" rel="noopener nofollow" target="_blank"><span class="blue-text">Track all markets on TradingView</span></a></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js" async>
    {
    "width": "980",
    "height": "610",
    "symbol": "NASDAQ:AAPL",
    "interval": "D",
    "timezone": "Etc/UTC",
    "theme": "light",
    "style": "1",
    "locale": "en",
    "allow_symbol_change": true,
    "calendar": false,
    "support_host": "https://www.tradingview.com"
  }
    </script>
  </div> -->
  <!-- TradingView Widget END -->



{% endblock %}

ASMA/tradingplatform/templates/marketview/index.html
{% extends "marketview/base.html" %}
{% load static %}
{% block body-block %}



    

    <script src="https://unpkg.com/@trevoreyre/autocomplete-js"></script>

    <div id="autocomplete" class="autocomplete container mt-3">
        <input class="autocomplete-input" placeholder="Search Symbols"/>
        <ul class="autocomplete-result-list"></ul>
    </div>

    <script>
        new Autocomplete('#autocomplete',{
            search: input =>{
                console.log(input)
                const url = '/marketview/search/?symbol='+(input)
                return new Promise(resolve =>{
                    fetch(url)
                    .then(response => response.json())
                    .then(data => {
                        resolve(data.data)
                    })
                })
            },
            onSubmit : result =>{
                window.open('/marketview/foreign_market/?symbol='+(result))
            }
        })
    </script> 

    <div class="container">
        <div class="row">
            <div class="col slogan">
                <h1 class="slogan-text">Strategy.</h1>
                <h1 class="slogan-text">Execution.</h1>
                <h1 class="slogan-text">Success.</h1>
            </div>
            <div class="col slogan2">
                <img src="{% static "marketview/homepg.png" %}" alt="" width="600">
            </div>
        </div>
    </div>



    <!-- TradingView Widget BEGIN -->

    <!-- <div class="tradingview-widget-container" style="height:100%;width:100%">
    <div class="tradingview-widget-container__widget" style="height:calc(100% - 32px);width:100%"></div>
    <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/" rel="noopener nofollow" target="_blank"><span class="blue-text">Track all markets on TradingView</span></a></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js" async>
        {
        "autosize": true,
        "symbol": "NASDAQ:AAPL",
        "interval": "D",
        "timezone": "Etc/UTC",
        "theme": "dark",
        "style": "1",
        "locale": "en",
        "allow_symbol_change": true,
        "calendar": false,
        "support_host": "https://www.tradingview.com"
      }
        </script>
  </div> -->
  <!-- TradingView Widget END -->
    
    <!-- <div class="pops container-fluid">
        <img src="{% static "marketview/pops-removebg-preview.png" %}" alt="" width="800">
    </div> -->

    <!-- <div class="chart">
        {{ fig|safe }}
    </div>
</div> -->


{% endblock %}

ASMA/tradingplatform/templates/marketview/login.html
{% extends 'marketview/base.html' %}

{% block body-block %}


<div class="jumbo container mt-3 shadow bg-gradient rounded-3">
    <h1>Please Login</h1>
    <form action="{% url 'marketview:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" class="btn bg-set text-set bg-gradient" value="Login">
    </form>
</div>

{% endblock %}

ASMA/tradingplatform/templates/marketview/news.html
{% extends "marketview/base.html" %}
{% load static %}
{% block body-block %}

<div class="container-fluid">

  {% if selected %}
    <div class="p-4 container">
      <h1 class="text-set3">News</h1>
    </div>

    {% if news_list %}
    <div class="d-flex flex-column">
      {% for news in news_list %}
      <div class="d-flex align-items-center">
        <div class="flex-shrink-0 p-3">
          <img src="{{ news.thumbnail }}" alt="Oops! Img Not Found.." width="600" height="400" >
        </div>
        <div class="flex-grow-1 ms-3">
          <p>{{ news.title }}.</p> 
          <p>{{ news.summary }}</p>
          <a href="{{ news.link }}"><em>From {{ news.source }}</em></a>
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <h1>No News Today!</h1>
    {% endif %}
  {% else %}
    <form action="{% url 'marketview:news' %}" method="post">
      {% csrf_token %}
      <label for="topic">Topic:</label>
      <select name="topic" id="topic">
        <option value="blockchain">Blockchain</option>
        <option value="earnings">Earnings</option>
        <option value="ipo">IPO</option>
        <option value="mergers_and_acquisitions">Mergers & Acquisitions</option>
        <option value="financial_markets">Financial Markets</option>
        <option value="economy_macro">Economy</option>
        <option value="energy_transportaion">Energy & Transportation</option>
        <option value="finance">Finance</option>
        <option value="life_sciences">Life Sciences</option>
        <option value="manufacturing">Manufacturing</option>
        <option value="real_estate">Real Estate & Construction</option>
        <option value="retail_wholesale">Retail & Wholesale</option>
        <option value="technology">Technology</option>
      </select>
      <input type="submit" class="btn bg-set text-set bg-gradient" value="GO">
    </form>
  {% endif %}


</div>
    
      



{% endblock %}

ASMA/tradingplatform/templates/marketview/newstopic.html
{% extends "marketview/base.html" %}

{% block body-block %}

<div class="jumbo container mt-3 shadow-lg bg-gradient rounded-3">

    <form action="" method="post">
      {% csrf_token %}  
      {{ select_topic.as_p }}
      <input type="submit" class="btn bg-set text-set bg-gradient" value="Submit">
    </form>

</div>
    
      



{% endblock %}

ASMA/tradingplatform/templates/marketview/registration.html
{% extends "marketview/base.html" %}
{% load static %}
{% block body-block %}

<div class="homepg">
    

    <div class="jumbo container mt-3 shadow-lg bg-gradient rounded-3">
        {% if registered %}
           <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Sign Up!</h1><br>
            <form method="post" enctype="multipart/form-data">
                {{ user_form.as_p }}
                {{ profile_form.as_p}}
                {% csrf_token %}
                <input type="submit" class="btn bg-set text-set bg-gradient" value="Register">
            </form>
        {% endif %}
    </div>
</div>


{% endblock %}

ASMA/tradingplatform/templates/marketview/search.html
{% extends 'marketview/base.html' %}

{% block body-block %}

<script src="https://unpkg.com/@trevoreyre/autocomplete-js"></script>

 <div id="autocomplete" class="autocomplete">
    <input class="autocomplete-input" />
    <ul class="autocomplete-result-list"></ul>
  </div>

  <script>
     new Autocomplete('#autocomplete',{
        search: input =>{
            console.log(input)
        }
     })
  </script>
 

<!-- <form action="" method="get">
    <label for="symbol">Search Symbols</label>
    <input type="text" name="symbol" id="symbol">
    <input type="submit" value="GO">
</form> -->
{% endblock %}